export * from './Page'
export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as CenterWrapper } from './centerWrapper'
export { default as Post } from './post'
